version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bot-tutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17rtxgtjbsujt"
s3_prefix = "bot-tutorial"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
